* CA

Det generelle koncept for CA-databasen er en en-til-en udvidelse af den enkelte tabel i CI med en ca-skema version. F.x. at der oprettes en ca.F_JOURNALNOTE tabel, en ca.F_JOURNALTABLE tabel osv.

ca-tabellen udvider modertabellen med en fra- og tildato, og en primaryKey. Fradato er dato for oprettelsestidspunkt (= createddate) og tildatoen er lig fradato for den næste version af rækken.
Referencen til ci-tabellen sker gennem id-kolonnen, som i Spider-databasen.
For hver række i ci-tabellen vil der være 1 til flere rækker i ca-tabellen incl. aktuelle række fra ci-tabellen, der også indgår i ca-tabellen.

En søgning efter data for en bestemt id-række i F_CONTACT på en bestemt dato f.x. 20. juni 2019 ville se ud som

#+BEGIN_EXAMPLE
SELECT * FROM ca.F_CONTACT
WHERE
  ca.fradato <= '2019-06-20' AND
 (ca.tildato >= '2019-06-20' OR ca.tildato IS NULL)
#+END_EXAMPLE

Såfremt data hentes fra flere ca-tabeller, skal metoden ovenfor tilsvarende anvendes på de øvrige tabeller.

Kriteriet for at indsætte række i ca-tabellen, er at den konkrete række er forskellig fra andre rækker med samme id i ca-tabellen. Dvs. det er en mere kompakt versionskoncept end Spiders, hvor hele strukturen kopieres i tilfælde af ændring.

De enkelte kolonner i tabellen er enten værdi kolonner eller id-kolonner. Id-kolonner er id-referencer til andre tabeller, f.x. Staff. Såfremt Id ikke ændres er der ikke grund til at indsætte en ny række i ca-tabellen. Historik på den refererede tabel håndteres på denne. Altså ca.Staff

Arkiveringsjobbet skal behandle de enkelte CI-tabeller der ønskes beriget med historik, og lave et tilsvarende udtræk mhp. at afklare om der er en betydende forskel.

** ID-kolonner og fremmednøgler
Modsat Spider3.databasen er der udbredt brug af fremmednøgler i CI-databasen. F.x. F_CONTACT-tabellen, der refererer til commitment, unit, term, staff mm. Hver af fremmednøglerelationerne er understøttet af et dedikeret index. Fremmednøglerelationerne sikrer sammenhæng (konsistens i data). Databaseindex begunstiger søgninger, men øger pladsbehov og tidsforbrug ved indsæt af rækker. CA databasen oprettes uden fremmednøglerelationer for at begunstige indsæt af data. Såfremt der er nogle af id-rækkerne i CA-tabellen, der refererer til ikke-eksisterende id'er i anden tabel, betragtes det ikke som en blokerende fejl. Det kan skyldes inkonsistens i Spider-databasen eller evt. manglende historik for denne entitet i CA-databasen, måske fordi der endnu ikke er dannet historik for tabellen.

Når CA-databasen er fuldt udfyldt vil det efterfølgende være muligt at danne de sql-index, der er ønskelig til brug for læsning. Evt. med inspiration fra indeks i CI-databasen.


* Journal

I Spiderdatabasen er journaloplysningerne er primært gemt i Datum-tabellerne, DatumServiceDatum (DSD), DatumServiceExternal (DSE) og DatumServiceHierarchical (DSH). Derudover er der RoS svar i TNG-tabeller og skabeloner i JournalForm tabeller og signeringsoplysninger i Bulk-tabellerne.

TNG- og Bulk-tabellerne indeholder prøvesvar mm i xml-format, der parses i CI's stored procedure så de kan normaliseres ud i kolonner. Det er derfor også nødvendigt for arkiveringsprojektet at lave en tilsvarende parsning, såfremt der er sket en ændring i TNG-referencen.

** JOURNALNOTE Journalnotater

                       +-------------------------------+
                       |                               |
                       |      F_JOURNALNOTE            |
                       |                               |
                       +-------------------------------+
                                      ^
                                      |
                                      |
                       +------------------------------------+
                       |                                    |
                       |      FE_JOURNALNOTE_ADMINISTRATION |
                       |                                    |
                       +------------------------------------+

*** F_JOURNALNOTE

F_JOURNALNOTE indeholder rækker af typen se.cambiosys.spider.JournalModule.JournalNote med udgangspunkt i DSD og DSE
F_JOURNALNOTE er den overordnede række for journalnotatet.

Tabellen indeholder type, subtype, status og en række id-referencer til Commitment, CareProvider mm

Tabellen indeholder allerede PrimaryKey.

Historiske id-rækker sammenligner med tidligere version og i tilfælde af ændring, f.x. Status eller CareProvider indsættes ny række


*** FE_JOURNALNOTE_ADMINISTRATION

Som F_JOURNALNOTE med mere specialiseret med signering


** JOURNALTABLE Prøvesvar


                       +-------------------------------+
                       |                               |
                       |      F_JOURNALTABLE           |
                       |                               |
                       +-------------------------------+
                                      ^
                                      |
                                      |
                       +-------------------------------+
                       |                               |
                       |      FC_JOURNALTABLE_COLUMN   |
                       |                               |
                       +-------------------------------+
                                      ^
                                      |
                                      |
                       +-------------------------------+
                       |                               |
                       |      FC_JOURNALTABLE_VALUE    |
                       |                               |
                       +-------------------------------+

*** F_JOURNALTABLE
F_JOURNALTABLE indeholder referencer til skabeloner og RoS prøvesvar fra Spider, med reference til spider3.TNGModuleTNG der indeholder xml gemt i binært format. Dvs. der sker en parsning af XML-strukturen.


*** FC_JOURNALTABLE_COLUMN
F_JOURNALTABLE_COLUMN har en en-til-mange relation til F_JOURNAL. Den består af JournalRecords gemt i DSD.


*** FC_JOURNALTABLE_VALUE
FC_JOURNALTABLE_VALUE har en reference til JOURNALTABLE_COLUMN og dermed til JOURNALTABLE,
Den indeholder oplysninger om de enkelte prøvesvar med referencer til JOURNALVALUE gemt som JournalRecords.
F.x Puls	30


** JOURNALFORM

                       +-------------------------------+
                       |                               |
                       |      D_JOURNALFORM            |
                       |                               |
                       +-------------------------------+
                                      ^
                                      |
                                      |
                       +-------------------------------+
                       |                               |
                       |      DC_JOURNALFORM           |
                       |                               |
                       +-------------------------------+


*** D_JOURNALFORM

F.x sårjournal.
Indeholder referencer til notater fra spider.JournalModuleJournalForm


*** DC_JOURNALFORM

Hierrarki af journalforme


** JOURNALVALUE

                       +-------------------------------+      +----------+
                       |                               |      |          |
                       |      F_JOURNALNOTE            |  --> |  Patient |
                       |                               |      |          |
                       +-------------------------------+      +----------+
                                      ^
                                      |
                                      |
                       +-------------------------------+      +----------------------+
                       |                               |      |                      |
                       |      F_JOURNALVALUE           | <--  | FC_JOURNALVALUE_CODE |
                       |                               |      |                      |
                       +-------------------------------+      +----------------------+
                                      ^
                                      |
                                      |
                       +-------------------------------+
                       |                               |
                       |      F_JOURNALVALUE_TEXT      |
                       |                               |
                       +-------------------------------+


*** FC_JOURNALVALUE
Indeholder journalrecords med 1-til-mange reference til JOURNALNOTE

*** FC_JOURNALVALUE_CODE

F.x.
Klassifikation af sygdomme:DE660H	DE660H	Ekstrem fedme, BMI 55+

mange til mange opløsning af Concept (ConceptServiceTerm / terminologier) og Journalværdier

*** FC_JOURNALVALUE_CODE_STAFF

mange til mange opløsning af Staff og JournalValue

De parses iøvrigt ud fra XML


*** F_JOURNALVALUE_TEXT

F_JOURNALVALUE_TEXT er en specialisering af FC_JOURNALVALUE, der indholder fritekst nøgleord

Tabellen referer til FC_JOURNALVALUE tabellen.
Tabellen beriges med til- og fradato.
Kriteriet for indsættelse er at value-feltet i DSD ændres.







                       +-------------------------------+      +----------+
                       |                               |      |          |
                       |      F_JOURNALNOTE            |  --> |  Patient |
                       |                               |      |          |
                       +-------------------------------+      +----------+
                                      ^
                                      |
                                      |
                       +-------------------------------+      +----------------------+
                       |                               |      |                      |
                       |      F_JOURNALVALUE           | <--  | FC_JOURNALVALUE_CODE |
                       |                               |      |                      |
                       +-------------------------------+      +----------------------+
                                      ^
                                      |
                                      |
                       +-------------------------------+
                       |                               |
                       |      F_JOURNALVALUE_TEXT      |
                       |                               |
                       +-------------------------------+


* User


#+BEGIN_EXAMPLE

                       +-------------------------------+      +----------------------+
                       |                               |      |                      |
                       |   D_STAFF                     | <--> | D_USER               |
                       |                               |      |                      |
                       +-------------------------------+      +----------------------+
                                      ^
                                      |
                                      |
                       +-------------------------------+
                       |                               |
                       |      DC_STAFF_IDENTIFIER      |
                       |                               |
                       +-------------------------------+
#+END_EXAMPLE


** D_STAFF

Stafftabellen indeholder oplysninger om medarbejderens rolle og underrolle (profession og subprofession). Brugerdata hentes fra spider3.UserServiceUser og rollerne fra spider3.ResourceServiceResource. Derudover er der en 1-til-1 relation til USER tabellen.
ca--tabellen beriges med historikkolonnerne, hvorefter tabellen kan indlæses

** DC_STAFF_IDENTIFIER

Staffidentifiertabellen indeholder oplysninger om medarbejderens cprnummer, autorisationskode mm. Der er dermed en 1-til-mange relation mellem STAFF og STAFF_IDENTIFIER.
Identifieroplysningerne hentes fra spider3.ResourceServiceExternal, der joines med spider3.ResourceServiceResource på vanlig vis.

** D_USER

Usertabellen indeholder oplysninger om brugerens oprettelse og status. Data hentes udelukkende fra spider3.UserServiceUser. Derudover er der en 1-til-1 relation til STAFF tabellen.
ca--tabellen beriges med historikkolonnerne, hvorefter tabellen kan indlæses


** D_USER_ROLE

Brugerrollerne hentes fra spider3.UserServiceRole. I denne tabel er der ikke noget latest-begreb, og dermed ikke historikspor. XYZ tjeck antal i UserServiceRole.


** D_GROUP

Patientgrupperne hentes udelukkende fra spider3.SubjectOfCareServiceGroup.
ca--tabellen beriges med historikkolonnerne, hvorefter tabellen kan indlæses




* Forløb, henvisninger og kontakter

I "Udkast CI tabeller til udvidelse" er anført historikbehov for henvisninger, men det er ikke angivet for forløb og kontakter

Data findes overvejende i de 3 tabeller: ActivityServiceActivity (ASA), ActivityServiceExternal (ASE) og ActivityServiceHierarchical (ASH).

Relationerne mellem forløb, henvisning og kontakter i CI er som følger

#+BEGIN_EXAMPLE
                          +-------------------------------+
                          |                               |
                          |   F_COMMITMENT                |
                          |                               |
                          +-------------------------------+
                                      ^                 ^
            +-------+                 |                 |
            |       V                 |                 |
            |   +----------------------------+     +-------------+
            |   |                            |     |             |
            +-- |      F_CONTACT             |---->|  F_REFFERAL |
                |                            |     |             |
                +----------------------------+     +-------------+
#+END_EXAMPLE

** Forløb, F_COMMITMENT

F_Commitment indeholder forløb med oplysninger om fra- og tildato henvisning til patient, enheder og medarbejdere (Performing og Responsible Unit/Staff) samt nogle statusmarkeringer, klassifikation mm.

Alt data hentes fra ASA, ASE og ASH incl. id-værdier for enheder og medarbejdere.

Ud over evt. ændringer til enheder og medarbejdere, vil forløbene historisk gennemløbe statusskift inden de oftest ender med status 164, se.cambiosys.spider.HealthCareModel.HCM_Closed.

Da der ikke er angivet ønske om historik på denne tabel, sker der ikke oprettelse af en historisk tabel i CI+ databasen.

*** Referencer
- Patient (ID)
- Group (ID)
- Responsible Unit (ID)
- Responsible Staff (ID)
- Pregnancy  (ID)
- ChildHealthcare (ID)
- PerformingUnit (ID)
- ExternalCommitment (ID)
- PerformingStaff (ID)
- Classification (DV_TERM)
- MotivationTerm (DV_TERM)
- Priority (DV_TERM)
- Status (D_HCM_STATUS)

** Henvisninger, F_REFFERAL

F_Referral indeholder henvisninger. Ligesom ved de øvrige tabeller, hentes data fra Spider-databasen fra ASA, ASE og ASH.
Derudover ligger henvisnininger i DatumServiceDatum gemt i xml-format som følger

#+BEGIN_EXAMPLE
<ClinicalInformation><Type>2</Type>
<SubType>0</SubType>
<Collection><PlannedTime>2017-10-20 16:06:40</PlannedTime>
<StartTime>2017-10-20 16:06:40</StartTime>
<EndTime>2017-10-20 16:06:40</EndTime>
<Unit/>
<IsDummyDate>0</IsDummyDate>
</Collection>
<CollectionType><Type><ID>1</ID>
<Description>Egen afdeling</Description>
</Type>
</CollectionType>
<Side>0</Side>
</ClinicalInformation>
#+END_EXAMPLE


Som ved commitment er der referencer til patient, enheder og medarbejdere (Performing og Responsible Unit/Staff) og RoS. Der er også en id-reference til commitment.
Der er samme statusmarkeringer, type 164 ("se.cambiosys.spider.HealthCareModel.HCM_Closed") og 160 ("se.cambiosys.spider.HealthCareModel.HCM_Cancelled"), og undervejs har tilstandende gennemløbet "se.cambiosys.spider.HealthCareModel.HCM_Planned" mm.

Der tilføjes fra- og tildato, således at historiske statusskift og ændringer fastholdes.

*** Referencer

- AdminCategory (DV_TERM)
- Category_1 (DV_TERM)
- Category_2 (DV_TERM)
- Commitment_ID
- Group_ID
- HCM_Status].[D_HCM_STATUS] ([Status_ID])
- InternalReferral_ID
- MedicalPriority (DV_TERM)
- MotivationTerm (DV_TERM)
- Patient_ID
- ReceivingStaff_ID
- ReceivingUnit_ID
- ReferralReferenceType (DV_TERM)
- ReferralType (DV_TERM)
- RequestForm_ID. (D_JOURNALFORM)
- RequestingContact_ID
- RequestingStaff_ID
- RequestingUnit_ID
- RequestNote_ID
- SourceOfReferral (DV_TERM)
- Status (D_REFERRAL_STATUS)
- Type (D_REFERRAL_TYPE)

** Kontakter

F_Contact tabellen er omfattende med 68 kolonner og mange join med ASE og Attribute-tabellerne. I AttributeServiceValue gemmes en række oplysninger, blandt andet om akut-værdi, planlagt, diskretion mm.

Der er ikke angivet behov for historik omkring kontakter,


*** Referencer
- AdminCategory (DV_TERM)
- AdmissionMethod (DV_TERM)
- AdmissionType (DV_TERM)
- AdmittedFromUnit_ID
- Agreement_ID
- CancellationReason (DV_TERM)
- CareReason (DV_TERM)
- Category_1 (DV_TERM)
- Category_2 (DV_TERM)
- CodeValidator (D_STAFF)
- Commitment_ID
- ConsultationType (DV_TERM)
- ContactType (D_CONTACT_TYPE)
- ContinuedCareplan (DV_TERM)
- CurrentLocation (DV_TERM)
- CustomerUnit_ID
- DelayedDischargeReason (DV_TERM)
- DischargedToUnit_ID
- DischargeMethod (DV_TERM)
- DischargeStaff_ID
- DischargeType (DV_TERM)
- FuturePriority (DV_TERM)
- Group_ID
- GroupContact_ID
- Identification (DV_TERM)
- JournalNote_ID
- JournalNoteStatus (D_JOURNAL_STATUS)
- Patient_ID
- PerformingStaff_ID
- PerformingUnit_ID
- ReasonNotCoded (DV_TERM)
- ResponsibleStaff_ID
- ResponsibleUnit_ID
- TargetPeriod (DV_TERM)
- TechnicalUnit_ID
- VisitType (DV_TERM)


* Medicin

Der er angivet historikbehov for følgende tabeller. Sammenhængen er illustreret nedenfor.

#+BEGIN_EXAMPLE

             +----------------------+    +-----------------------------+          +----------------------------+
             |                      |    |                             |          |                            |
             | FC_MEDICATION_DOSAGE |--> |  F_MEDICATION               |<---------| F_MEDICATION_ADMIN         |
             |                      |    |                             |          |                            |
             +----------------------+    +-----------------------------+          +----------------------------+
                                           ^              |                               ^
                                           |              V                               |
                     +-----------------+   |          +------------+                 +----------------------------+
                     |                 |   |          |            |                 |                            |
                     |  F_PRESCRIPTION |---+          |  D_DRUG    |<----------------| FC_MEDICATION_ADMIN        |
                     |                 |              |            |                 |                            |
                     +-----------------+              +------------+                 +----------------------------+
                                                            |
                                                            V
                                                      +------------+
                                                      |            |
                                                      | D_ATC      |
                                                      |            |
                                                      +------------+

#+END_EXAMPLE



** Lægemiddelstofklassifikation,  ATC
Data om atc-klassifikationer til tabellen D_ATC hentes fra spider3.ConceptServiceConcept og -ConceptServiceTerm og fra spider3.ResourceServiceResource (lokale koder).

I D_ATC er der reference til hierarkiske atc værdier, men ikke ydeligere referencer

Der tilføjes historikkolonner.


** Lægemiddel, D_DRUG
Tabellen D_DRUG hentes fra spider3.ResourceServiceResource samt spider3.AttributeService.
I tabellen gemmes oplysning om beskrivelse, styrke mm.

Drugtabellen har en reference til ATC-værdi og en eksterns product_id, men ingen ydeligere referencer til øvrige tabeller i CI.

Der tilføjes historikkolonner.

** Medicinering, F_MEDICATION

Tabellen D_MEDICATION udfyldes primært med data fra spider3.ASA og ASE og fra spider3.DSD og DSE. Datum-tabellerne indeholder oplysninger om MedicationDatum.

Der er oplysninger om status, indikation, formål mm.

Der tilføjes historikkolonner.

*** Referencer
- Patient (ID)
- Contact (ID)
- Drug (ID),
- Creating og Responsible Unit (ID)
- Creating og Responsible Staff (ID)
- Signer (ID)


** Ordination, F_PRESCRIPTION

Ordinationsoplysningerne i F_MEDICATION udfyldes ligeledes med oplysninger fra spider3.ASA, ASE og DSD tabeller.

Den indeholder oplysning om iteration, interval, fee mm

Der tilføjes historikkolonner.

*** Referencer
- Patient (ID)
- Contact (ID)
- Medication (ID),
- Creating og Responsible Unit (ID)
- Creating Staff (ID)
- Signer (ID)
- ePrescription (ID)

** Dosis, FC_MEDICATION_DOSAGE

F_MEDICATION_DOSAGE indeholder oplysninger dosisdelen af F_MEDICATION. Data parses ud fra en xml-struktur hentet fra DatumServiceDatum eller BulkServiceBulk. Det er ikke trivielt at normalisere data ud i dosistabellen.

Dosisoplysningerne er volument, iteration, duration, maxdosage mm

Der tilføjes historikkolonner.

*** Referencer
- Medication (ID)


** Administrering, F_MEDICATION_ADMIN
F_MEDICATION_ADMIN indholder oplysninger om administrering af medicin, bl.a. om dose.
Data hentes fra ASA og ASE tabeller. Detailoplysninger om dosis parses fra XML-struktur.

Der tilføjes historikkolonner.

*** Referencer
- Patient (ID)
- Medication (ID)
- Creating Unit (ID)


** Administreringshændelse, FC_MEDICATION_ADMIN
I FC_MEDICATION_ADMIN er der oplysninger om den enkelte administration af medicin. Data hentes fra spider3.DSD tabellerne. Prescription-oplysninger hentes fra xml-struktur i DSD

Der tilføjes historikkolonner.

*** Referencer
- Patient (ID)
- MedicationAdmin (ID),
- Unit (ID)
- Staff (ID)
- Signer (ID)


* Bulkdata

I Spider3 databasen anvendes BulkServiceBulk-tabellen til fælles opbevaring af binær data. Fremgangsmåden er at xml-strukturer, Officedokumenter, billeder, lydfiler (tidligere) mm. bliver gemt i binære format i kolonnen bulkData, der er af sql-typen 'image'. Imagetypen erstattes fremover af Varbinary(max). Bulkservicebulktabellen er større end 1Tb incl indeks.

Bulkservicebulk har en type-værdi, der angiver formatet af bulkData, og en id-værdi, der fungerer som reference til de øvrige tabeller.
F.x se.cambiosys.spider.MedModule.Med_DosageXml typen, der indeholder dosis-oplysninger til FC_MEDICATION_DOSAGE. I dette tilfælde referer BulkServiceBulk.id til DSD.value

Der oprettes en CA.Bulk tabel, der svarer til Spider3.BulkServiceBulk tabellen. Der opsættes en selvstændigt sql-job, der kopierer rækker fra Spider3.BulkServiceBulk til CA.Bulk ud de ønskede bulktyper.
Dvs. bulktyper som Med_DosageXml ovenfor er ikke relevante, da de på anden måde indgår i CA. Dictation er heller ikke relevante.
Derimod er JournalWordDocument, JournalDocument m.fl. relevante.
De præcise bulktyper der ønskes medtaget fastlægges under udviklingen af scriptet.
Id-kolonnen indgår i CA.Bulk, så det er muligt at navigere gennem denne.

** Oversigt over bulktyper
- se.cambiosys.client.framework.menueditor.BulkType
- se.cambiosys.client.framework.patients.photo.BulkType
- se.cambiosys.client.framework.phrase.BulkType
- se.cambiosys.client.framework.publicholiday.BulkType
- se.cambiosys.client.framework.relatives.BulkType
- se.cambiosys.client.framework.report.BulkType
- se.cambiosys.client.framework.SaveWindowsLayout.BulkType
- se.cambiosys.client.framework.subjectofcare.BulkType
- se.cambiosys.client.framework.version.ClientVersionsBulkType
- se.cambiosys.client.growthchart.pluginConfigurations
- se.cambiosys.client.overviewmodule.OVM_StartPageConfigs
- se.cambiosys.spider.AgreementModule.CA_Product_Class_Availability
- se.cambiosys.spider.AgreementModule.CA_Product_Class_Markup
- se.cambiosys.spider.BirthModule.JournalView
- se.cambiosys.spider.CareAdministrationModule.CA_ProductRulesBulkType
- se.cambiosys.spider.CareAdministrationModule.CA_RequestRuleBulkType
- se.cambiosys.spider.CareAdministrationModule.CA_RequestRuleConfigBulkType
- se.cambiosys.spider.CareAdministrationModule.TransactionRefBulk
- se.cambiosys.spider.CareAdministrationModule.valuables.BulkType
- se.cambiosys.spider.ClinicalCoding.CC_ModuleCodeTree
- se.cambiosys.spider.DictationModule.DictationCategory.BulkDictation
- se.cambiosys.spider.DictationModule.DictationCategory.BulkLetter
- se.cambiosys.spider.HealthCareModel.HCM_ReferralCodesBulk
- se.cambiosys.spider.JournalModule.CareReasonSetting
- se.cambiosys.spider.JournalModule.CD_XMLTree
- se.cambiosys.spider.JournalModule.DefaultValuesForTreatmentPlan
- se.cambiosys.spider.JournalModule.JournalDocument
- se.cambiosys.spider.JournalModule.JournalFilter
- se.cambiosys.spider.JournalModule.JournalFormTree
- se.cambiosys.spider.JournalModule.JournalValueDataType
- se.cambiosys.spider.JournalModule.JournalView
- se.cambiosys.spider.JournalModule.JournalWordDocument
- se.cambiosys.spider.MedModule.Med_DosageXml
- se.cambiosys.spider.MedModule.Med_Unit_Template
- se.cambiosys.spider.MedSchemeModule.Med_General_Directive
- se.cambiosys.spider.MedSchemeModule.Med_Time_Setting
- se.cambiosys.spider.OfferService.Offer_Scheme_Type
- se.cambiosys.spider.OfferService.OfferSet_Scheme_Model_Type
- se.cambiosys.spider.OfferService.Resource_Scheme_Type
- se.cambiosys.spider.OrderManagementModule.OM_ClinicalInformation_Bulk
- se.cambiosys.spider.OrderManagementModule.OM_CommentBulk
- se.cambiosys.spider.OrderManagementModule.OM_ResultBulk
- se.cambiosys.spider.OrderProductModule.OrderProductCodesBulk
- se.cambiosys.spider.PDFFormModule.FDF
- se.cambiosys.spider.PDFFormModule.PDF
- se.cambiosys.spider.PlanActionModule.RP_Care_Information
- se.cambiosys.spider.PlanActionModule.RP_CodeTreeBulk
- se.cambiosys.spider.PlanActionModule.RP_FreeText_Bulk
- se.cambiosys.spider.PsychiatricModule.JournalView
- se.cambiosys.spider.ScheduleModule.ScheduleCalendarSettingType
